📋 Página de créditos
enflujo/imagina-inclusion-migrantes pull request #56
Opened 2024-05-01 01:40 UTC by Juliansintilde

Tuve un pequeño problema con los cortes de los cueris. 
No supe cómo llamar el archivo de constantes la página de `Créditos`. 
Los cargué directamente en el CSS de la página de créditos mientras tanto.

2024-05-01 01:51 UTC, Juliansintilde commented
Me sale este error en el pull requuest pero no sé cómo corregirlo :/

![image](https://github.com/enflujo/imagina-inclusion-migrantes/assets/42554838/d8d4cce1-018d-4aa8-a642-acf705bdaf3f)

2024-05-01 02:42 UTC, 1cgonza requested changes

2024-05-01 02:42 UTC, 1cgonza commented on aplicaciones/www/src/estaticos/_constantes.scss
> +  $minCelular: 576px;
estas variables de SCSS no va dentro de `:root{}`

2024-05-01 02:42 UTC, 1cgonza commented on aplicaciones/www/src/paginas/Creditos.vue
> +/// Medidas porque no supe cómo traerlas desde 'constantes.scss'
`@import '../estaticos/constantes';`

2024-05-01 02:42 UTC, 1cgonza commented on aplicaciones/www/src/paginas/Creditos.vue
> +      <img class="logoImagina logoGrande" src="/imgs/Imagina.webp" alt="Logo Centro IMAGINA"
este logo tiene fondo blanco y usar `mix-blend-mode: multiply;` no funciona en todos los exploradores. Hay que exportarlo de nuevo.

El logo de los andes no tiene el mismo tamaño entre esta y la de EnFlujo, no importa como se pongan, no quedan alineados. Toca alinearlos, cualquiera de los dos.

2024-05-01 02:42 UTC, 1cgonza commented on aplicaciones/www/src/paginas/Creditos.vue
> +  height: 180px;
me parece que quedan demasiado grandes los logos en pantallas grandes.

2024-05-01 02:42 UTC, 1cgonza commented on aplicaciones/www/src/paginas/Creditos.vue
> +    mix-blend-mode: multiply;
`mix-blend-mode: multiply;` quitar esto que no tiene buena compatibilidad en exploradores, preferible exportar la img sin fondo para evitar problemas.

2024-05-01 02:42 UTC, 1cgonza commented on aplicaciones/www/src/paginas/Creditos.vue
> +    font-size: 1vw;
no usar `vw` para el tamaño de la letra, se crece demasiado en pantallas grandes. Contener en usar `em` o `px` para controlar mejor el espacio que ocupa la letra en diferentes pantallas.

2024-05-01 02:42 UTC, 1cgonza commented on aplicaciones/www/src/paginas/Creditos.vue
> +      height: auto;
si algo se pone idéntico en muchas partes se debe sacar al más general. Por fuera de los `@media`, parece que `height: auto` se usa en todos los logos.

2024-05-01 02:44 UTC, 1cgonza commented
> 🎌Auxilio: @1cgonza @anattolia Me sale este error en el pull requuest pero no sé cómo corregirlo :/ Ya le corrí prettier pero parece que todo está bien. Y no toqué el archivo `tsconfig.json`.

@Juliansintilde ya está resuelto en `main`, entonces con un rebase ya no sale ese error.

2024-05-01 14:14 UTC, Juliansintilde commented on aplicaciones/www/src/paginas/Creditos.vue
> +    font-size: 1vw;
Esta propuesta la probé varias veces y no me parece mala idea para pantallas exponencialmente grandes sobre las que no tenemos control. Eso lo pensé viendo páginas viejas que estaban diseñadas máximo para 1024x768 en la clase de Anto, jeje. Me explico:

Con los cortes que tenemos en las páginas que diseñamos casi siempre dejamos ajustado para pantallas HD o FullHD igual que para una pantalla 4K. Cosa que de por sí es rara, ¿no? porque en su pantalla 4K se nota mucho la diferencia y los textos quedan muy muy pequeños frente al tamaño de la pantalla. Al menos eso creo yo. Podemos definir un `em` de letra entonces para las 4K, pero nunca pensamos en las 8 K... y supongamos que luego haya otra y otra más grande... es un escenario loco, pero ¿qué tal si nos adelantamos a eso?

Me parece que dejar las páginas configurables solo a partir del zoom es pensar que todxs lxs usuarios usan eso y no es así.

En fin, quizá la solución del `vw` no es la mejor porque bloquea la opción de hacer zoom out, pero sí me parece que hay algo que podemos mejorar frente a los cortes y el tamaño de las cosas en las pantallas más grandes.

Hago el cambio igual pero chévere que lo pensemos.

2024-05-01 14:30 UTC, 1cgonza commented on aplicaciones/www/src/paginas/Creditos.vue
> +    font-size: 1vw;
@Juliansintilde bien, hay que balancear entre esos dos: que sirva en pantallas a futuro pero que no elimine funcionalidades como el zoom.

2024-05-03 20:04 UTC, Juliansintilde commented on aplicaciones/www/src/paginas/Creditos.vue
> +    font-size: 1vw;
@1cgonza  Creo que por aquí va la cosa: https://css-tricks.com/optimizing-large-scale-displays/ (lo puedo empezar ya después del merge para no enredar la cosa)

2024-05-08 14:49 UTC, merged